name: Auto-update news

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up git
        run: |
          git config --global user.name "news-bot"
          git config --global user.email "news-bot@example.com"

     - name: Update news files
  run: |
    python src/googlenewsscraper/rss_to_blog_styled.py

- name: Commit changes
  run: |
    git add public
    git commit -m "Auto-update news" || echo "No changes to commit"

- name: Push changes
  run: |
    git push origin HEAD:main
